name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip install -U pip
          pip install mkdocs-material mkdocs-material-extensions mkdocs-autorefs mkdocstrings poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Deploy docs
        run: mkdocs gh-deploy --force
        working-directory: docs